title: Jiyoung Cheong
logo: /assets/img/profile_photo.jpg
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
show_sidebar: true

plugins:
  - jekyll-toc

toc:
  min_level: 1
  max_level: 3
  ordered_list: false
